# Copyright (c) 2026, Liangyu Zhang
# SPDX-License-Identifier: BSD-3-Clause
"""Public model-oriented APIs for the PowerModels backend."""

from .acp import ACPModel, build_acp_model, solve_acp_model, solve_acp_opf
from .acr import ACRModel, build_acr_model, solve_acr_model, solve_acr_opf
from .act import ACTModel, build_act_model, solve_act_model, solve_act_opf
from .bf import (
    BFAModel,
    SOCBFModel,
    build_bfa_model,
    build_socbf_model,
    solve_bfa_model,
    solve_bfa_opf,
    solve_socbf_model,
    solve_socbf_opf,
)
from .conic import (
    SDPWRMModel,
    SOCBFConicModel,
    SOCWRConicModel,
    SparseSDPWRMModel,
    build_sdpwrm_model,
    build_socbf_conic_model,
    build_socwr_conic_model,
    build_sparse_sdpwrm_model,
    solve_sdpwrm_model,
    solve_sdpwrm_opf,
    solve_socbf_conic_model,
    solve_socbf_conic_opf,
    solve_socwr_conic_model,
    solve_socwr_conic_opf,
    solve_sparse_sdpwrm_model,
    solve_sparse_sdpwrm_opf,
)
from .constraints import (
    constraint_active_generation_sum,
    constraint_branch_active_power_bounds,
    constraint_branch_apparent_power_limit,
    constraint_branch_reactive_power_bounds,
    constraint_gen_active_bounds,
    constraint_gen_reactive_bounds,
    constraint_gen_setpoint_active,
    constraint_gen_setpoint_reactive,
    constraint_interface_active_power,
    constraint_voltage_angle_difference,
    constraint_voltage_magnitude_bounds,
    constraint_voltage_magnitude_setpoint,
)
from .dcmp import DCMPModel, build_dcmp_model, solve_dcmp_model, solve_dcmp_opf
from .dcp import (
    DCPLLModel,
    DCPModel,
    NFAModel,
    build_dcp_model,
    build_dcpll_model,
    build_nfa_model,
    solve_dcp_model,
    solve_dcp_opf,
    solve_dcpll_model,
    solve_dcpll_opf,
    solve_nfa_model,
    solve_nfa_opf,
)
from .dispatch import (
    FORMULATIONS,
    build_power_model,
    solve_built_power_model,
    solve_formulation_opf,
    solve_power_models_opf,
)
from .extensions import PowerModel, PowerModelExtension, PowerModelExtensionCallback
from .ivr import IVRModel, build_ivr_model, solve_ivr_model, solve_ivr_opf
from .lpacc import LPACCModel, build_lpacc_model, solve_lpacc_model, solve_lpacc_opf
from .qc import (
    QCLSModel,
    QCRMModel,
    build_qcls_model,
    build_qcrm_model,
    solve_qcls_model,
    solve_qcls_opf,
    solve_qcrm_model,
    solve_qcrm_opf,
)
from .socwr import SOCWRModel, build_socwr_model, solve_socwr_model, solve_socwr_opf

__all__ = [
    "ACPModel",
    "ACRModel",
    "ACTModel",
    "BFAModel",
    "DCMPModel",
    "DCPLLModel",
    "DCPModel",
    "IVRModel",
    "LPACCModel",
    "NFAModel",
    "QCLSModel",
    "QCRMModel",
    "SDPWRMModel",
    "SOCBFConicModel",
    "SOCBFModel",
    "SOCWRConicModel",
    "SOCWRModel",
    "SparseSDPWRMModel",
    "FORMULATIONS",
    "PowerModelExtension",
    "PowerModel",
    "PowerModelExtensionCallback",
    "build_acp_model",
    "build_acr_model",
    "build_act_model",
    "build_bfa_model",
    "build_dcmp_model",
    "build_dcpll_model",
    "build_dcp_model",
    "build_ivr_model",
    "build_lpacc_model",
    "build_nfa_model",
    "build_qcls_model",
    "build_qcrm_model",
    "build_sdpwrm_model",
    "build_socbf_conic_model",
    "build_socbf_model",
    "build_socwr_conic_model",
    "build_socwr_model",
    "build_sparse_sdpwrm_model",
    "build_power_model",
    "constraint_active_generation_sum",
    "constraint_branch_active_power_bounds",
    "constraint_branch_apparent_power_limit",
    "constraint_branch_reactive_power_bounds",
    "constraint_gen_active_bounds",
    "constraint_gen_reactive_bounds",
    "constraint_gen_setpoint_active",
    "constraint_gen_setpoint_reactive",
    "constraint_interface_active_power",
    "constraint_voltage_angle_difference",
    "constraint_voltage_magnitude_bounds",
    "constraint_voltage_magnitude_setpoint",
    "solve_acp_model",
    "solve_acp_opf",
    "solve_acr_model",
    "solve_acr_opf",
    "solve_act_model",
    "solve_act_opf",
    "solve_bfa_model",
    "solve_bfa_opf",
    "solve_dcmp_model",
    "solve_dcmp_opf",
    "solve_dcpll_model",
    "solve_dcpll_opf",
    "solve_dcp_model",
    "solve_dcp_opf",
    "solve_ivr_model",
    "solve_ivr_opf",
    "solve_lpacc_model",
    "solve_lpacc_opf",
    "solve_nfa_model",
    "solve_nfa_opf",
    "solve_qcls_model",
    "solve_qcls_opf",
    "solve_qcrm_model",
    "solve_qcrm_opf",
    "solve_sdpwrm_model",
    "solve_sdpwrm_opf",
    "solve_socbf_conic_model",
    "solve_socbf_conic_opf",
    "solve_socbf_model",
    "solve_socbf_opf",
    "solve_socwr_conic_model",
    "solve_socwr_conic_opf",
    "solve_socwr_model",
    "solve_socwr_opf",
    "solve_sparse_sdpwrm_model",
    "solve_sparse_sdpwrm_opf",
    "solve_power_models_opf",
    "solve_built_power_model",
    "solve_formulation_opf",
]
